name: ibaji
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  flutter_naver_map: ^1.2.3+1
  google_maps_flutter: ^2.5.0
  http: ^0.13.5
  json_serializable: ^6.6.1
  flutter_svg: ^1.1.6
  flutter_localization: ^0.1.11
  logger: ^1.3.0
  geocoding: ^2.1.0
  fluttertoast: ^8.2.2
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  camera: ^0.10.5+2
  dio: ^5.2.1
  flutter_launcher_icons: ^0.12.0
  image_picker: ^0.8.7
  freezed: ^2.3.7
  freezed_annotation: ^2.4.1
  flutter_image_compress: ^2.0.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.14
  flutter_lints: ^2.0.3
  kakao_flutter_sdk_user: ^1.6.1
  transparent_image: ^2.0.1
  dotted_border: ^2.1.0
  fdottedline_nullsafety: ^2.0.1
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  change_app_package_name: ^1.1.0
  scroll_to_index: ^3.0.1
  spider: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.8
  json_annotation: ^4.8.1
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - asset/image/icon/
    - asset/image/images/


  
  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: asset/fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: asset/fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: asset/fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: asset/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: asset/fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: asset/fonts/Pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/Pretendard/Pretendard-Black.ttf
          weight: 900
  
